#porta do server
server:
 port: 8888

spring:
 application:
   name: cloud-config

# irá ler os arquivos.yml localmente
 profiles:
   active:
   - native
 cloud:
   config:
     server:
       git:
         uri: https://github.com/hakacarol/microservices_udemy
         #username:
         #password:
         default-label: main
         search-paths:
           - 'cloud-config'
